import { useQuery } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import { api } from '../api/client'
import { ExcludedWorkRow } from './ExcludedWorkRow'
import { PageHeader } from './ui/PageState'
import { Card } from './ui/Card'
import { Meter } from './ui/Meter'

function formatRupees(n: number): string {
  return `Rs. ${n.toLocaleString('en-IN')}`
}

export function BudgetSimulator() {
  const { data: defaultAlloc } = useQuery({ queryKey: ['allocation-default'], queryFn: () => api.allocation() })
  const [budget, setBudget] = useState<number | null>(null)

  useEffect(() => {
    if (defaultAlloc && budget === null) setBudget(defaultAlloc.budget)
  }, [defaultAlloc, budget])

  const { data: alloc, isFetching } = useQuery({
    queryKey: ['allocation', budget],
    queryFn: () => api.allocation(budget!),
    enabled: budget !== null,
  })

  const { data: allWorks } = useQuery({ queryKey: ['works-all'], queryFn: () => api.works(500) })

  const maxBudget = defaultAlloc ? defaultAlloc.budget * 2 : 300_000_000

  const excludedWorks = (() => {
    if (!allWorks || !alloc) return []
    const fundedIds = new Set(alloc.selected_works.map((w) => w.work_id))
    return allWorks.filter((w) => !fundedIds.has(w.work_id)).slice(0, 8)
  })()

  return (
    <div className="mx-auto max-w-3xl px-4">
      <PageHeader title="Budget Simulator" subtitle="Drag the slider to see how the allocator's picks change with the MPLADs limit." />

      <Card className="p-5">
        <div className="mb-2 flex items-center justify-between">
          <label htmlFor="mplads-budget-slider" className="text-sm font-medium text-stone-700 dark:text-stone-300">
            MPLADs annual limit
          </label>
          <span className="font-display text-lg font-medium tabular-nums text-stone-900 dark:text-stone-50">
            {budget != null ? formatRupees(budget) : '...'}
          </span>
        </div>
        <input
          id="mplads-budget-slider"
          type="range"
          min={0}
          max={maxBudget}
          step={100000}
          value={budget ?? 0}
          onChange={(e) => setBudget(Number(e.target.value))}
          aria-valuetext={budget != null ? formatRupees(budget) : undefined}
          className="w-full accent-accent-700"
        />
        {defaultAlloc && (
          <p className="mt-1 text-xs text-stone-400">
            Default is Bagalkot's real current (18th Lok Sabha) MPLADs allocated limit: {formatRupees(defaultAlloc.budget)}
          </p>
        )}

        {alloc && (
          <div className="mt-4 grid grid-cols-3 gap-3 border-t border-stone-200 pt-4 dark:border-stone-800">
            <Stat label="Works funded" value={alloc.n_works_selected.toString()} />
            <div className="text-center">
              <div className="font-display text-xl font-medium tabular-nums text-stone-900 dark:text-stone-50">
                {Math.round(alloc.budget_used_pct * 100)}%
              </div>
              <div className="text-xs text-stone-500 dark:text-stone-400">Budget used</div>
              <Meter value={alloc.budget_used_pct} className="mt-1.5" />
            </div>
            <Stat label="Total priority value" value={alloc.total_value.toFixed(1)} />
          </div>
        )}
        {isFetching && <p className="mt-2 text-xs text-stone-400">Recomputing allocation...</p>}
      </Card>

      {alloc && (
        <>
          <p className="mt-4 text-xs text-stone-500 dark:text-stone-400">{alloc.cost_heuristic_note}</p>
          <div className="mt-3 flex flex-col gap-2">
            {alloc.selected_works.slice(0, 15).map((w) => (
              <div
                key={w.work_id}
                className="flex items-center justify-between rounded-md border border-stone-200 bg-stone-50 px-3 py-2 text-sm dark:border-stone-800 dark:bg-stone-900"
              >
                <div>
                  <span className="font-medium text-stone-900 dark:text-stone-100">{w.village_name}</span>
                  <span className="ml-2 text-stone-500 dark:text-stone-400">({w.theme})</span>
                </div>
                <span className="tabular-nums text-stone-600 dark:text-stone-400">{formatRupees(w.cost)}</span>
              </div>
            ))}
            {alloc.selected_works.length > 15 && (
              <p className="text-xs text-stone-400">...and {alloc.selected_works.length - 15} more works funded.</p>
            )}
          </div>
        </>
      )}

      {excludedWorks.length > 0 && (
        <div className="mt-6">
          <h3 className="mb-2 text-sm font-semibold text-stone-900 dark:text-stone-50">
            Excluded works — why weren't they funded?
          </h3>
          <p className="mb-3 text-xs text-stone-500 dark:text-stone-400">
            Each explanation is generated by an LLM (NVIDIA base model, Claude backup) and verified: every number it
            cites must match the real score/cost data, or it falls back to a template built from the same real values.
          </p>
          <div className="flex flex-col gap-2">
            {excludedWorks.map((w) => (
              <ExcludedWorkRow key={w.work_id} work={w} budget={budget} />
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="text-center">
      <div className="font-display text-xl font-medium tabular-nums text-stone-900 dark:text-stone-50">{value}</div>
      <div className="text-xs text-stone-500 dark:text-stone-400">{label}</div>
    </div>
  )
}
