"""add sanitation fields to village_fact

Revision ID: 162ee44308a4
Revises: 633b0d572b60
Create Date: 2026-07-05 15:58:17.606880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '162ee44308a4'
down_revision: Union[str, Sequence[str], None] = '633b0d572b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (spurious drop_index for the 3 manually-managed expression indexes removed -- see
    # migration c2172e1c09fd; not represented in model metadata, false positive every time)
    op.add_column('village_fact', sa.Column('has_closed_drainage', sa.Boolean(), nullable=True))
    op.add_column('village_fact', sa.Column('has_no_drainage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('village_fact', 'has_no_drainage')
    op.drop_column('village_fact', 'has_closed_drainage')
    # ### end Alembic commands ###
