"""add photo_path to submission

Revision ID: 393f7334a114
Revises: 162ee44308a4
Create Date: 2026-07-08 21:42:21.943427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '393f7334a114'
down_revision: Union[str, Sequence[str], None] = '162ee44308a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate wanted to drop ux_census_pca_village_natural_key/idx_pmgsy_*_geog
    # here too -- same false positive as 633b0d572b60 (manually-managed expression indexes
    # invisible to SQLAlchemy's model metadata). Removed; do not drop them.
    op.add_column('submission', sa.Column('photo_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'photo_path')
    # ### end Alembic commands ###
