"""submission and issue tables

Revision ID: 633b0d572b60
Revises: c2172e1c09fd
Create Date: 2026-07-05 15:37:24.520523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '633b0d572b60'
down_revision: Union[str, Sequence[str], None] = 'c2172e1c09fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.Enum('water', 'road', 'school', 'health', 'electricity', 'sanitation', 'other', name='theme_enum'), nullable=False),
    sa.Column('village_code', sa.Integer(), nullable=True),
    sa.Column('representative_text', sa.Text(), nullable=False),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_code'], ['lgd_village.village_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Enum('voice', 'text', 'photo', name='channel_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('theme', sa.Enum('water', 'road', 'school', 'health', 'electricity', 'sanitation', 'other', name='theme_enum'), nullable=False),
    sa.Column('place_text', sa.String(length=256), nullable=True),
    sa.Column('resolved_lgd_code', sa.Integer(), nullable=True),
    sa.Column('place_match_score', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['resolved_lgd_code'], ['lgd_village.village_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate wanted to drop ux_census_pca_village_natural_key/idx_pmgsy_*_geog here
    # -- those are the manually-managed expression indexes from migration c2172e1c09fd, which
    # SQLAlchemy's model metadata can't see (they're not represented by any model). Removed as
    # false positives; do not drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('issue')
    # ### end Alembic commands ###
