"""census mplads pmgsy schools boundary tables

Revision ID: 86e66016ea24
Revises: d75d686658cf
Create Date: 2026-07-05 15:10:27.646364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '86e66016ea24'
down_revision: Union[str, Sequence[str], None] = 'd75d686658cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('census_pca_village',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('district_serial', sa.Integer(), nullable=False),
    sa.Column('subdistt_serial', sa.Integer(), nullable=True),
    sa.Column('town_vill_code', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tru', sa.String(length=16), nullable=False),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('male_population', sa.Integer(), nullable=True),
    sa.Column('female_population', sa.Integer(), nullable=True),
    sa.Column('literate_population', sa.Integer(), nullable=True),
    sa.Column('illiterate_population', sa.Integer(), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('main_workers', sa.Integer(), nullable=True),
    sa.Column('marginal_workers', sa.Integer(), nullable=True),
    sa.Column('non_workers', sa.Integer(), nullable=True),
    sa.Column('lgd_village_code', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('census_village_amenities',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=128), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=128), nullable=True),
    sa.Column('village_name', sa.String(length=256), nullable=False),
    sa.Column('cd_block_name', sa.String(length=128), nullable=True),
    sa.Column('gram_panchayat_name', sa.String(length=128), nullable=True),
    sa.Column('total_geographical_area_ha', sa.Float(), nullable=True),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('male_population', sa.Integer(), nullable=True),
    sa.Column('female_population', sa.Integer(), nullable=True),
    sa.Column('sc_population', sa.Integer(), nullable=True),
    sa.Column('st_population', sa.Integer(), nullable=True),
    sa.Column('govt_primary_schools', sa.Integer(), nullable=True),
    sa.Column('pvt_primary_schools', sa.Integer(), nullable=True),
    sa.Column('govt_middle_schools', sa.Integer(), nullable=True),
    sa.Column('pvt_middle_schools', sa.Integer(), nullable=True),
    sa.Column('govt_secondary_schools', sa.Integer(), nullable=True),
    sa.Column('pvt_secondary_schools', sa.Integer(), nullable=True),
    sa.Column('govt_sr_secondary_schools', sa.Integer(), nullable=True),
    sa.Column('pvt_sr_secondary_schools', sa.Integer(), nullable=True),
    sa.Column('primary_health_centre_count', sa.Integer(), nullable=True),
    sa.Column('primary_health_subcentre_count', sa.Integer(), nullable=True),
    sa.Column('community_health_centre_count', sa.Integer(), nullable=True),
    sa.Column('has_treated_tap_water', sa.Boolean(), nullable=True),
    sa.Column('has_hand_pump', sa.Boolean(), nullable=True),
    sa.Column('has_tube_well', sa.Boolean(), nullable=True),
    sa.Column('has_covered_well', sa.Boolean(), nullable=True),
    sa.Column('has_closed_drainage', sa.Boolean(), nullable=True),
    sa.Column('has_open_drainage', sa.Boolean(), nullable=True),
    sa.Column('has_no_drainage', sa.Boolean(), nullable=True),
    sa.Column('has_pucca_road', sa.Boolean(), nullable=True),
    sa.Column('has_all_weather_road', sa.Boolean(), nullable=True),
    sa.Column('has_kuchha_road', sa.Boolean(), nullable=True),
    sa.Column('has_national_highway', sa.Boolean(), nullable=True),
    sa.Column('has_state_highway', sa.Boolean(), nullable=True),
    sa.Column('domestic_power_supply', sa.Boolean(), nullable=True),
    sa.Column('domestic_power_hours_summer', sa.Float(), nullable=True),
    sa.Column('domestic_power_hours_winter', sa.Float(), nullable=True),
    sa.Column('has_commercial_bank', sa.Boolean(), nullable=True),
    sa.Column('has_cooperative_bank', sa.Boolean(), nullable=True),
    sa.Column('has_atm', sa.Boolean(), nullable=True),
    sa.Column('has_shg', sa.Boolean(), nullable=True),
    sa.Column('nearest_town_name', sa.String(length=256), nullable=True),
    sa.Column('nearest_town_distance_km', sa.Float(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_table('know_your_school',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('udise_code', sa.String(length=16), nullable=False),
    sa.Column('school_name', sa.String(length=256), nullable=False),
    sa.Column('district_name', sa.String(length=128), nullable=False),
    sa.Column('block_name', sa.String(length=128), nullable=True),
    sa.Column('village_name', sa.String(length=256), nullable=True),
    sa.Column('village_cd', sa.String(length=32), nullable=True),
    sa.Column('mgmt_desc', sa.String(length=128), nullable=True),
    sa.Column('category_desc', sa.String(length=128), nullable=True),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('lgd_village_id', sa.Integer(), nullable=True),
    sa.Column('lgd_village_name', sa.String(length=256), nullable=True),
    sa.Column('matched_lgd_village_code', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('mplads_allocated_limit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('constituency', sa.String(length=128), nullable=False),
    sa.Column('mp_name', sa.String(length=256), nullable=False),
    sa.Column('allocated_amount', sa.BigInteger(), nullable=False),
    sa.Column('lok_sabha_term', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mplads_expenditure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=128), nullable=False),
    sa.Column('work_title', sa.String(length=512), nullable=False),
    sa.Column('vendor_name', sa.String(length=256), nullable=True),
    sa.Column('ida', sa.String(length=256), nullable=True),
    sa.Column('mp_name', sa.String(length=256), nullable=False),
    sa.Column('constituency', sa.String(length=128), nullable=False),
    sa.Column('lok_sabha_term', sa.String(length=16), nullable=False),
    sa.Column('expenditure_date', sa.Date(), nullable=True),
    sa.Column('work_status', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mplads_work',
    sa.Column('work_code', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('work_title', sa.String(length=512), nullable=False),
    sa.Column('ida', sa.String(length=256), nullable=True),
    sa.Column('mp_name', sa.String(length=256), nullable=False),
    sa.Column('constituency', sa.String(length=128), nullable=False),
    sa.Column('lok_sabha_term', sa.String(length=16), nullable=False),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('recommended_amount', sa.BigInteger(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('sanction_stage', sa.String(length=64), nullable=True),
    sa.Column('sanction_amount', sa.BigInteger(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('completed_rating', sa.String(length=32), nullable=True),
    sa.Column('completed_amount', sa.BigInteger(), nullable=True),
    sa.Column('matched_lgd_village_code', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('work_code')
    )
    op.create_table('pc_boundary',
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('st_name', sa.String(length=64), nullable=False),
    sa.Column('pc_no', sa.Integer(), nullable=False),
    sa.Column('pc_name', sa.String(length=128), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('pc_id')
    )
    op.create_table('pmgsy_habitation',
    sa.Column('hab_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('hab_name', sa.String(length=256), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('is_coord_valid', sa.Boolean(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('hab_id')
    )
    op.create_table('pmgsy_road_drrp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('er_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('road_code', sa.String(length=64), nullable=True),
    sa.Column('road_category', sa.String(length=16), nullable=True),
    sa.Column('road_name', sa.String(length=256), nullable=True),
    sa.Column('road_owner', sa.String(length=32), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pmgsy_road_proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mrl_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('lgd_district_code', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('cn_code', sa.Float(), nullable=True),
    sa.Column('proposed_length_km', sa.Float(), nullable=True),
    sa.Column('work_name', sa.String(length=512), nullable=True),
    sa.Column('ims_year', sa.String(length=32), nullable=True),
    sa.Column('proposal_type', sa.String(length=8), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pmgsy_road_proposal')
    op.drop_table('pmgsy_road_drrp')
    op.drop_table('pmgsy_habitation')
    op.drop_table('pc_boundary')
    op.drop_table('mplads_work')
    op.drop_table('mplads_expenditure')
    op.drop_table('mplads_allocated_limit')
    op.drop_table('know_your_school')
    op.drop_table('census_village_amenities')
    op.drop_table('census_pca_village')
    # ### end Alembic commands ###
