"""village fact table

Revision ID: b293414ba8cc
Revises: 86e66016ea24
Create Date: 2026-07-05 15:16:53.332036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b293414ba8cc'
down_revision: Union[str, Sequence[str], None] = '86e66016ea24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('village_fact',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=256), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=128), nullable=True),
    sa.Column('gram_panchayat_name', sa.String(length=128), nullable=True),
    sa.Column('district_name', sa.String(length=128), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('sc_population', sa.Integer(), nullable=True),
    sa.Column('st_population', sa.Integer(), nullable=True),
    sa.Column('literate_population', sa.Integer(), nullable=True),
    sa.Column('illiterate_population', sa.Integer(), nullable=True),
    sa.Column('literacy_rate', sa.Float(), nullable=True),
    sa.Column('pca_match_score', sa.Float(), nullable=True),
    sa.Column('census_school_count', sa.Integer(), nullable=True),
    sa.Column('kys_school_count', sa.Integer(), nullable=True),
    sa.Column('health_facility_count', sa.Integer(), nullable=True),
    sa.Column('has_treated_tap_water', sa.Boolean(), nullable=True),
    sa.Column('has_safe_water_source', sa.Boolean(), nullable=True),
    sa.Column('has_pucca_road', sa.Boolean(), nullable=True),
    sa.Column('has_all_weather_road', sa.Boolean(), nullable=True),
    sa.Column('pmgsy_connected', sa.Boolean(), nullable=True),
    sa.Column('domestic_power_hours_summer', sa.Float(), nullable=True),
    sa.Column('domestic_power_hours_winter', sa.Float(), nullable=True),
    sa.Column('mplads_completed_amount_total', sa.BigInteger(), nullable=True),
    sa.Column('mplads_completed_work_count', sa.Integer(), nullable=True),
    sa.Column('mplads_recommended_amount_total', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['village_code'], ['lgd_village.village_code'], ),
    sa.PrimaryKeyConstraint('village_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('village_fact')
    # ### end Alembic commands ###
