"""lgd backbone tables

Revision ID: d75d686658cf
Revises: 
Create Date: 2026-07-05 15:03:45.174806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d686658cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgd_district',
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=128), nullable=False),
    sa.Column('census2001_code', sa.String(length=16), nullable=True),
    sa.Column('census2011_code', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('district_code')
    )
    op.create_table('lgd_local_body',
    sa.Column('localbody_code', sa.Integer(), nullable=False),
    sa.Column('localbody_type_name', sa.String(length=64), nullable=False),
    sa.Column('localbody_name', sa.String(length=256), nullable=False),
    sa.Column('parent_localbody_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_localbody_code'], ['lgd_local_body.localbody_code'], ),
    sa.PrimaryKeyConstraint('localbody_code')
    )
    op.create_table('lgd_block',
    sa.Column('block_code', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=128), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['lgd_district.district_code'], ),
    sa.PrimaryKeyConstraint('block_code')
    )
    op.create_table('lgd_subdistrict',
    sa.Column('subdistrict_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_name', sa.String(length=128), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('census2001_code', sa.String(length=16), nullable=True),
    sa.Column('census2011_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['lgd_district.district_code'], ),
    sa.PrimaryKeyConstraint('subdistrict_code')
    )
    op.create_table('lgd_village',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=256), nullable=False),
    sa.Column('village_name_local', sa.String(length=256), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=False),
    sa.Column('subdistrict_code', sa.Integer(), nullable=True),
    sa.Column('census2001_code', sa.String(length=16), nullable=True),
    sa.Column('census2011_code', sa.String(length=16), nullable=True),
    sa.Column('village_status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['district_code'], ['lgd_district.district_code'], ),
    sa.ForeignKeyConstraint(['subdistrict_code'], ['lgd_subdistrict.subdistrict_code'], ),
    sa.PrimaryKeyConstraint('village_code')
    )
    op.create_index(op.f('ix_lgd_village_census2011_code'), 'lgd_village', ['census2011_code'], unique=False)
    op.create_table('lgd_village_gp_mapping',
    sa.Column('village_code', sa.Integer(), nullable=False),
    sa.Column('local_body_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['local_body_code'], ['lgd_local_body.localbody_code'], ),
    sa.ForeignKeyConstraint(['village_code'], ['lgd_village.village_code'], ),
    sa.PrimaryKeyConstraint('village_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lgd_village_gp_mapping')
    op.drop_index(op.f('ix_lgd_village_census2011_code'), table_name='lgd_village')
    op.drop_table('lgd_village')
    op.drop_table('lgd_subdistrict')
    op.drop_table('lgd_block')
    op.drop_table('lgd_local_body')
    op.drop_table('lgd_district')
    # ### end Alembic commands ###
